version: '3.1'
services:
        joomla:
                image: joomla
                restart: always
                links:
                        - joomladb:mysql
                ports:
                        - 8080:80
                environment:
                        JOOMLA_DB_HOST: joomladb
                        JOOMLA_DB_PASSWORD: hello
                volume:
                        -joom_storage: /var/www/html
        joomladb:
                image: mysql:5.7
                restart: always
                environment:
                        MYSQL_ROOT_PASSWORD: hello
                volumes:
                        - mysql_storage: /var/lib/mysql/data

volumes:                          
        joom_storage:
        mysql_storage:



                       

